#!/bin/bash

# Function to check the status of the SSL Labs scan
check_scan_status() {
    scan_status=$(curl -s "https://api.ssllabs.com/api/v3/analyze/${1}?all=done" | jq -r '.status')
    echo "$scan_status"
}

# Function to initiate an SSL Labs scan for a given host
initiate_scan() {
    curl -s "https://api.ssllabs.com/api/v3/analyze?host=${1}&all=done" > /dev/null
}

# Read the file containing the list of websites
hosts_file="ssl.txt"

while IFS= read -r host
do
    echo "Scanning SSL certificate for $host"

    initiate_scan "$host" # Initiate the scan

    status=$(check_scan_status "$host") # Check the status of the scan

    # Wait until the scan is completed
    while [ "$status" != "READY" ]
    do
        if [ "$status" == "IN_PROGRESS" ]; then
            echo "Scan in progress. Waiting..."
        else
            echo "Scan failed or encountered an error."
            break
        fi

        sleep 10s # Wait for 10 seconds before checking the status again
        status=$(check_scan_status "$host")
    done

    if [ "$status" == "READY" ]; then
        echo "Scan completed for $host"
        # Perform additional actions with the scan results if needed
    fi

    echo "-------------------------"

done < "$hosts_file"
